### PR TITLE
add py

### PR DESCRIPTION
**Pull request by nick1udwig**
In order to add support for Python, we need to update dependencies. This PR does that. It is associated with https://github.com/uqbar-dao/process_lib/pull/7 and https://github.com/uqbar-dao/uqdev/pull/3

### CODE REVIEW

**Comment by nick1udwig** [comment]
See https://github.com/hosted-fornet/py-chat for an example app you can build.

**Comment by dr-frmr** [comment]
Nice! This cause any build issues in the runtime? Looks good to me...

**Review by dr-frmr — APPROVED** [review]
good fix in that error print

**Comment by nick1udwig** [comment]
> Nice! This cause any build issues in the runtime? Looks good to me...

Builds for me :+1:

**Pull request merged**
